### PR TITLE
Add Composer support

### PR DESCRIPTION
**Pull request by egeloen**
Hey!

First thank for your work, it really save my time :) 

I propose to add your lib on [packagist](https://packagist.org/) to ease integration in large project as explain in #3

### CODE REVIEW

**Comment by egeloen** [comment]
ping @ornicar

**Comment by ornicar** [comment]
Would you like to maintain this repository? I could give you push credentials.

**Comment by egeloen** [comment]
@ornicar Yep :)

**Comment by ornicar** [comment]
done. Congrats.

**Comment by egeloen** [comment]
^^

**Pull request merged**
